version:  "3.8"
services:
  mysqldb:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todosdb
      MYSQL_USER: przemek
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
  app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MY_HOST: mysqldb
      MY_DB: todosdb
      JWT_SECRET: ilikeyou
    restart: always

